---
apiVersion: v1
kind: Service
metadata:
  name: [[project_name]]-services
  labels:
    app: [[project_name]]
    app.kubernetes.io/instance: [[project_name]]-services
spec:
  ports:
    - port: 80
      targetPort: 3000
      name: nodejs
      protocol: TCP
  selector:
    app: [[project_name]]